
version: 2

models:
    - name: src_orders
      description: "A starter dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

